apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-container-deployment
  labels:
    app: helloContainer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloContainer
  template:
    metadata:
      labels:
        app: helloContainer
    spec:
      containers:
        - name: hello-container
          image: antsala/hellocontainer_cicd:<pon_la_etiqueta>
          ports:
            - containerPort: 8080